### ISSUE TITLE
MailCore not appearing in Xcode project

### ISSUE THREAD

**Issue by bottlehall** [LiveUI/MailCore#7]
I've got an existing Vapor 3 project that I would like to extend to include MailCore. I added the line to Package.swift and accepted the rebuild Xcode project and re-started it. The MailCore dependency doesn't appear in the list of dependencies or targets. If I look inside the .build folder, the repository folder `MailCore.git-295220472883278198` exists and has a reasonable-looking set of contents. I've run `vapor Xcode` separately from `vapor update`.

I'm running the latest version of Xcode and the existing project is running on latest Vapor and swift 4.2. I'm by no means an expert on swift packaging. The only difference I can see is that all my other dependencies use `from` rather than `.branch`, so I tried putting in `from: "0.2.2"` but to no avail. Any help in getting this working would be gratefully received.

**Comment by rafiki270** [comment]
Have you deleted the package resolve file too?

**Comment by bottlehall** [comment]
Thanks for your reply. No, I hadn't, but I tried renaming it and doing `vapor update` again, but no difference.

I suddenly remembered that, for most, extensions, you also need to add to the targets as well and putting "MailCore" into this array has made `MailCore and `Mailgun` appear.
